function [A, B]=return_after_RH2NMF(trainset, testset,gnd,beta1,beta2,alpha,HW_DATA,HW_fea)
nClass = length(unique(gnd));
fea =trainset;
[m,n] = size(fea);
LL = ConstructHCFW(fea,m,6);
LL=abs(LL);
intau=rand(m,nClass);
intau = intau./(ones(m,1)*sum(intau,1));
intav=rand(nClass,n);
options = [];
maxiter = 100;
options.meanFitRatio = 0.1;
option.dis=true;
option.iter=200;
options.error = 1e-5;   
option.residual=1e-4;
option.tof=1e-4;  
option.alpha=alpha;    
option.beta1=beta1; 
L = ConstructHCFW(fea',n,6);
L=abs(L);

[U,~] = RH2DNMF(fea, beta2, maxiter, intau, intav,option, L,LL, gnd);
U = ((U'*U)\U')';
A=trainset'*U;   
A=A';        
B=testset'*U;  
B=B';  
